### ISSUE TITLE
Italic descriptors for fused rings (nomenclature)

### ISSUE THREAD

**Issue by Jellby** [cgnieder/chemmacros#11]
Is there an easy way (other than `\textit{b}`) to input a lowercase italic letter inside a `\iupac` command? This is needed for fused ring systems: http://www.acdlabs.com/iupac/nomenclature/79/r79_63.htm#a_21__5 http://www.acdlabs.com/iupac/nomenclature/93/r93_74.htm

If not, consider this a feature request.

**Comment by cgnieder** [comment]
You can always add new IUPAC commands yourself (if that would suit your needs):

```latex
\documentclass{article}
\usepackage{chemmacros}

\NewChemIUPAC\aa{\textit{a}}
\NewChemIUPAC\jj{\textit{j}}

\begin{document}

\iupac{Benzo[\aa]anthracene}
\iupac{Dibenz[\aa,\jj]anthracene}

\end{document}
```

**Comment by cgnieder** [comment]
Myself I'd probably use a custom command:

```latex
\documentclass{article}
\usepackage{chemmacros}

\newcommand*\fuse[1]{\textit{#1}}

\begin{document}

\iupac{Benzo[\fuse{a}]anthracene}
\iupac{Dibenz[\fuse{a},\fuse{j}]anthracene}

\end{document}
```
