### ISSUE TITLE
Line breaking after parentheses followed by hyphens leads to double dash

### ISSUE THREAD

**Issue by basseur** [cgnieder/chemmacros#13]
I came across the following problem:

Line breaking after parentheses adds a hyphen of course. However, when a hyphen is already present in this position, a redundant hyphen is still produced.

![unbenannt](https://user-images.githubusercontent.com/32487587/31378731-8255a2d8-adac-11e7-97ef-7c6a4f3fb9d0.JPG)

```
\documentclass{scrbook}

\usepackage{chemmacros}
\chemsetup{modules={nomenclature}}

\begin{document}
\huge\iupac{SomeVeryLongNameWithParentheses-(Followed)-ByHyphens}
\end{document}
```

An example for where this occurred was _[1,1'-biphenyl]-4,4'-dicarboxylic acid_.

**Comment by cgnieder** [comment]
Thanks. I will look into it.
