### ISSUE TITLE
[Spectroscopy Module] Option to change 'range-phrase' in 'experimental' environment

### ISSUE THREAD

**Issue by lcnittl** [cgnieder/chemmacros#15]
Is there a way to change the `range-phrase` for every `experimental` environment, without changing it in the whole document?

If not, I think an option to do so would be quite handy, and more practical than adding `\sisetup{range-phrase = <newrangephrase>}` in every `experimental` environment (especially considering consistency).

**Comment by cgnieder** [comment]
`chemmacros` loads `etolbox` so you ahould be able to use

    \AtBeginEnvironment{experimental}{\sisetup{ ... }}

**Comment by lcnittl** [comment]
Yes, that's doing the job. Maybe you could add a hint in the manual.

Thanks a lot!
