### ISSUE TITLE
Incompatibility between nomenclature module and subfiles package

### ISSUE THREAD

**Issue by sverl** [cgnieder/chemmacros#19]
There seems to be a bug regarding the compatibility between the nomenclature module and the subfiles package. While the main document compiles with the module, the subfile does not. It seems like this is only a problem with the nomenclature module as other modules work fine. 

Versions: chemmacros 45164 (5.8b), subfiles 26645 (1.1) with latex/pdflatex/xelatex 

# MWE 
## main.tex
```
\documentclass[]{article}

\usepackage{subfiles}
\usepackage{upgreek}
\usepackage{chemmacros}

\begin{document}
	\subfile{sub}
\end{document}
```

## sub.tex
```
\documentclass[main.tex]{subfiles}

\begin{document}
	% commands working in both documents
	\pH
	\insitu 
	\ch{A -> B}
	\iupac{abc}
	\iupac{ab\chemgamma}
	
	% commands working only in main document
	\dexter
	\iupac{abc^1}
	\iupac{ab-c}
	\iupac{ab(c)}
	\iupac{ab[c]}
\end{document}
```
### Output from sub.tex
```
! Undefined control sequence.
l.12	\dexter
```
and analogously for the rest of the control sequences.

**Comment by cgnieder** [comment]
My guess is that this happens because most iupac commands are defined when `\begin{document}` happens. I have no idea how `subfiles` works but there are probably limits…

I'm not sure how to procede here, to be honest.

**Comment by cgnieder** [comment]
This seems to be resolved – the current version gives works fine for me:

```latex
\documentclass[]{article}

\usepackage{subfiles}
\usepackage{upgreek}
\usepackage{chemmacros}

\begin{filecontents}[overwrite]{test-sub.tex}
\documentclass[test.tex]{subfiles}
\begin{document}
% commands working in both documents
1: \pH\
2: \insitu\
3: \ch{A -> B}
4: \iupac{abc}
5: \iupac{ab\chemgamma}

% commands working only in main document
1: \dexter\
2: \iupac{abc^1}
3: \iupac{ab-c}
4: \iupac{ab(c)}
5: \iupac{ab[c]}
\end{document}
\end{filecontents}

\begin{document}

\subfile{test-sub}

1: \dexter\
2: \iupac{abc^1}
3: \iupac{ab-c}
4: \iupac{ab(c)}
5: \iupac{ab[c]}

\end{document}
```

![image](https://user-images.githubusercontent.com/2248538/73611593-981ab000-45e3-11ea-8086-7ae478b34436.png)
