### ISSUE TITLE
Redefinition of pre-defined Latin phrases is unintuitive

### ISSUE THREAD

**Issue by moewew** [cgnieder/chemmacros#22]
See https://tex.stackexchange.com/q/447242/35864

Since the three pre-defined Latin phrases are only defined in `\AtBeginDocument`, the way to redefine them can be quite unintuitive.
```
\documentclass{article}
\usepackage{chemmacros}
\RenewChemLatin\insitu{in-situ}
\begin{document}
  \insitu
\end{document}
```
Throws an unexpected error. Replacing `\RenewChemLati` with `\NewChemLatin` does not help either.

Maybe the documentation could mention the `\AtBeginDocument` or (I like that even better) the definition could be made in the normal flow of code and not in `\AtBeginDocument`.

**Comment by cgnieder** [comment]
I am aware of this and the reason I chose this is the definition of a command with the same name name for the same usage by the package `chemstyle`. I hesitate to change the current behavious but I must admit that I am undecided about the issue…

**Comment by cgnieder** [comment]
I decided to go for it, i.e., get rid of `\AtBeginDocument`.
