### ISSUE TITLE
Incompatibility with sticky-per setting of siunitx

### ISSUE THREAD

**Issue by ipatrol** [cgnieder/chemmacros#23]
Attempting to set the `sticky-per` option of `siunitx` at any time before or after loading `chemmacros` causes one of several errors. Either there's an option conflict, or the package's use of `\per` causes a `duplicate-sticky-per` error.

I'm not sure if there's any solution given the lack of proper namespacing in LaTeX, but it might be at least worth documenting.

**Comment by cgnieder** [comment]
I cannot reproduce this. The following works fine for me:

```latex
\documentclass{article}
\usepackage{chemmacros}
\usepackage{siunitx}
\sisetup{sticky-per}

\begin{document}

bla bla \SI{2.3}{\candela\per\kWh}

\end{document}
```
