### ISSUE TITLE
Explanation of translations in manual

### ISSUE THREAD

**Issue by marijnschraagen** [cgnieder/chemmacros#24]
The current manual (v5.8b 2017/08/28) explains the use of the `\DeclareChemTranslation` macro on page 31 (section 6.5.2). It states:
```latex
\DeclareChemTranslation{language}{key}{translation}
```
In the table with available translation keys (Table 3 on page 31) the keys `scheme-name`, `scheme` and `Scheme` are listed, among many others.

However, given the following MWE (see https://tex.stackexchange.com/questions/494010/chemmacros-scheme-translation):
```latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[spanish]{babel}

\usepackage{chemmacros}
\chemsetup{modules={scheme}}

\DeclareChemTranslation{spanish}{scheme-name}{Esquema} % 1
\DeclareChemTranslation{scheme-name}{spanish}{Esquema} % 2
\DeclareChemTranslation{spanish}{scheme}{Esquema}      % 3
\DeclareChemTranslation{scheme}{spanish}{Esquema}      % 4

\begin{document}

    \begin{scheme}
        \caption{Lorem ipsum}
    \end{scheme}

\end{document}
```
Variant 1 and 3, which should be valid according to the manual, fail with an error ``! Package translations Error: Unknown language `scheme-name'.`` and ``Unknown language `scheme'``. In https://github.com/cgnieder/chemmacros/blob/725c7d93626d846313bb71e9ec9ff0a3b271fea2/chemmacros.module.lang.code.tex#L118 the order is stated as
```latex
% #1: key
% #2: lang
% #3: translation
```
but the code the call to `\declaretranslation` uses the arguments in the order 2, 1, 3. So maybe the manual should be updated, or the code, I'm not sure what would be the easiest or best solution.

For the other two variants in the MWE the redefinition of `scheme` does not work, there are no errors but the caption of `scheme` environments remains in English, or in German if that is the language of the document. The variant that redefines `scheme-name` works as expected (no errors and the caption changes). Possibly the manual could clarify which translation key should be used?

**Comment by cgnieder** [comment]
That's an error in the manual. correct is:

```latex
% #1: key
% #2: lang
% #3: translation
```
I'll fix this for the next update
