### ISSUE TITLE
Symbol for torr

### ISSUE THREAD

**Issue by rafaelpap** [cgnieder/chemmacros#27]
I believe the symbol for the torr unit should be Torr. The units module define it as
\DeclareSIUnit {\torr      } {torr}
whereas it should be 
\DeclareSIUnit {\torr      } {Torr}

The IUPAC green book says
![image](https://user-images.githubusercontent.com/45312334/68581041-f0746280-0477-11ea-8312-1ac8a6b003d1.png)

**Comment by cgnieder** [comment]
Thanks. I implemented it.

**Comment by rafaelpap** [comment]
I am puzzled by your new definition. Why the name Torr instead of torr?

**Comment by cgnieder** [comment]
That's the whole point, isn't it? Or (in case you are talking about the control sequence) in order to match existing symbols like `\Pa`.

One might argue, though, that since there is also a `\pascal` there should be a `\torr`, too.

Is that what you are puzzled about?

**Comment by rafaelpap** [comment]
Exactly, the name is torr and the symbol is Torr. Similarly, name pascal and symbol Pa.Anyway, I thank you for the chemistry packages. They allow me to write quickly paying attention to content.
null
