### ISSUE TITLE
NMR module: solvent containing a hyphen (-) will produce minus sign

### ISSUE THREAD

**Issue by tstone-1** [cgnieder/chemmacros#28]
The mwe.tex

```latex
% arara: pdflatex

\documentclass{article}
\usepackage{chemmacros}
\chemsetup{
	compatibility/compatibility=5.10,
	modules={spectroscopy},
}

\begin{document}

The preferred NMR solvent is DMSO-d\textsubscript{6}. Could also be \ch{DMSO-d\textsubscript{6}}, but doesn't look nice. What about \ch{ "DMSO-d\textsubscript{6}" } or \ch[minus-output-symbol=-]{DMSO-d\textsubscript{6}}?

\begin{experimental}[list=true,format=\bfseries]
\NMR{31,P[^1H]}(162,\mega\hertz)[DMSO-d\textsubscript{6}]~[ppm] = 
\val{34.0}.
\end{experimental}

\begin{experimental}[list=true,format=\bfseries]
\NMR{31,P[^1H]}(162,\mega\hertz)[ "DMSO-d\textsubscript{6}" ]~[ppm] = 
\val{34.0}.
\end{experimental}

\end{document}
```

will produce

![Screenshot 2020-02-15 19 35 29](https://user-images.githubusercontent.com/48162401/74593339-67e30080-502a-11ea-9399-b77ff80293e3.png)

where the minus sign within the 31P-NMR line doesn't fit. I suppose that the sovent part within brackets is typeset as if it was put into `\ch{}`. That's why I tried to add `"..."` to escape text input - However, no luck yet. I also tried to alter `minus-output-symbol` as suggested in the manual but found no visual impact on the output...? Thanks for helping!

e/ Oops, now I posted this on chemformula where it better fits chemmacros, I guess. Can you move it to chemmacros or should I repost it to chemmacros...?

**Comment by cgnieder** [comment]
I transfered the issue.

The problem is that `chemmacros` uses the internal equivalent of `chemfomula`'s `\chcpd`. This command treats everything as one single formula and knows nothing about the escaping mechanism. The dash is interpreted as a single bond.

The simplest solution would be to just hide it:

```latex
\documentclass{article}
\usepackage{chemmacros}
\chemsetup{ modules={spectroscopy} }

\newcommand*\dash{-}

\begin{document}

\begin{experimental}[list=true,format=\bfseries]
  \NMR{31,P[^1H]}(162,\mega\hertz)[DMSO\dash d6]~[ppm] = \val{34.0}.
\end{experimental}

\end{document}
```

Another way would be to actually use `\ch` (maybe `chemmacros` should do this anyway?):

```latex
\documentclass{article}
\usepackage{chemmacros}
\chemsetup{ modules={spectroscopy} }

\begin{document}

\ExplSyntaxOn
\cs_set_protected:Npn \chemmacros_chemformula:n #1
  { \chemformula_ch:nn {} {#1} }
\ExplSyntaxOff

\begin{experimental}[list=true,format=\bfseries]
  \NMR{31,P[^1H]}(162,\mega\hertz)[DMSO "-" d6]~[ppm] = \val{34.0}.
\end{experimental}

\end{document}
```

**Comment by tstone-1** [comment]
Both of your solutions look fine! To me, the general usage of `\ch` for the NMR solvent seems useful. Typical examples could be true chemical formulae like CDCl3, CD2Cl2, C6D6. When substitutional formulae like DMSO-d6, Acetone-d6, MeOD-d3 can be typeset, all possible NMR solvents should be covered, I guess.

Could you briefly explain why `\ch[minus-output-symbol=-]{DMSO-d\textsubscript{6}}` outside of the `experimental` environment will still interpret `-` as `$-$`?

**Comment by cgnieder** [comment]
The dash represents three different things for `chemformula`: a minus sign in charges, a single bond, and a minus sign as relation. The last one only works in `\ch` and not in `\chcpd` and it is the only one that is modified with `minus-output-symbol`.

```latex
\documentclass{article}
\usepackage{chemformula}
\begin{document}

1: \ch{-} 2: \chcpd{A-} 3: \chcpd{A-B} 4: \ch{A-B - A+B + C}

\setchemformula{minus-output-symbol=:}
1: \ch{-} 2: \chcpd{A-} 3: \chcpd{A-B} 4: \ch{A-B - A+B + C}

\hrulefill

\newcommand*\dash{-}
\chcpd{CDCl3} \chcpd{CD2Cl2} \chcpd{C6D6}
\chcpd{DMSO\dash d6} \chcpd{Acetone\dash d6} \chcpd{MeOD\dash d3}

\end{document}
```

![image](https://user-images.githubusercontent.com/2248538/74682107-6ac62880-51c5-11ea-9552-682be6b93cbb.png)
