### ISSUE TITLE
Float Creation

### ISSUE THREAD

**Issue by lcnittl** [cgnieder/chemmacros#29]
Is there a way to override detection (cf. snippet) of float creation method (e.g. _via_ an option in the `scheme` module?

https://github.com/cgnieder/chemmacros/blob/489695fbe9f752fa70984408b815856f0db8875c/chemmacros.module.scheme.code.tex#L132-L135

I am currently forced to work with a `scrbook` implementation `sr-vorl` and do not manage to tweak the list of schemes to have the same formatting as the list of figures and list of tables. Adjust scheme numbering to within chapter (using the anyways loaded package `chngcntr`), successfully alters numbering, but the `indent` and `numwidth`do not match.

```
\usepackage{chemmacros}

<...>

\chemsetup{
    modules = {
        nomenclature,
        reactions,
        redox,
        scheme,
        spectroscopy,
        units,
    },
    formula = mhchem,
}
\chemsetup[mhchem]{
    arrows = pgf-filled,
    textminus                    = {--},
    minus-text-sidebearing-left  = {0.04em},% For dashed bonds
    minus-text-sidebearing-right = {0.08em},% For dashed bonds
    minus-math-sidebearing-left  = {0.04em},
    minus-math-sidebearing-right = {0.08em},
}
\chemsetup[redox]{
    explicit-sign = true,
    explicit-zero-sign = true,
    decimal-marker = comma,
    roman = false,
    pos = top,
}
\chemsetup[spectroscopy]{
    format = \bfseries,
    pos-number=super,
}
\chemsetup[nomenclature]{
    coord-use-hyphen = {false},
}

<...>

\AtBeginDocument{\counterwithout{scheme}{chapter}}
\AtBeginDocument{\counterwithin{scheme}{chapter}}
```

Although, I guess the `KOMA` method should be used already in this case (using a `KOMA` class) and I don't really understand why the list of schemes does not fit the format.

I was hoping that using a different creation method would help me overcoming that issue.

Or would you advise to manually define the float before chemmacros gets to do it?

```
\DeclareNewTOC[
    type = scheme ,
    types = schemes ,
    float ,
    name = Scheme ,
    listname = {List of Schemes},
    counterwithin=chapter
]{scheme}
```

**Comment by cgnieder** [comment]
The scheme is only defined at the end of the preamble if it doesn't exist before,

You should be fine defining it yourself using any method you want.

**Comment by lcnittl** [comment]
Ok, thanks for your reply! For now I'll go with:

```
  \DeclareNewTOC[
    type = scheme,
    types = schemes,
    float,
    name = Scheme,
    listname = {List of Schemes},
    counterwithin=chapter,
    tocentryindent=1.5em,
    tocentrynumwidth=2.3em,
  ]{los}
  \setuptoc{scheme}{chapteratlist}
```

I don't know why one has to explicitly add `tocentryindent` and `tocentrynumwidth` (otherwise numbers with 2 digits will clash with the caption) to make the formatting the same. (But I guess that is an issue to `basictoc`)

Can it yet be beneficial to have an option to override automatic detection as this allows usage of all `chemmacros` internal variables and definition (including translations) for the `scheme` float.

**Comment by cgnieder** [comment]
> 
> Can it yet be beneficial to have an option to override automatic detection as this allows usage of all `chemmacros` internal variables and definition (including translations) for the `scheme` float?
> 

I'm not sure this is even possible for all or any of the implemented methods.
