### ISSUE TITLE
Einbinden des Pakets erzeugt 100+ Fehler

### ISSUE THREAD

**Issue by ryder1977** [cgnieder/chemmacros#3]
\documentclass[a4paper,twoside,10pt]{report}
\usepackage{chemmacros}
\begin{document}
Einbinden funktioniert nicht.
\end{document}

Alleine das Einbinden des Paketes erzeugt über 100 Fehler bei einem Lauf mit MikTex. 

! Undefined control sequence.
<argument> Chem\str_upper_case:f 
                                 {\tl_head:n {alpha}}\str_lower_case:f {\tl_...
l.449 \chemgreek_drop_symbols:
                              
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

**Comment by cgnieder** [comment]
Hast Du etwa `chemgreek` aktualisiert, ohne die TeX-Distribution als ganzes zu aktualisieren? `\str_upper_case:f` wurde am ersten März 2015 zu expl3 hinzugefügt und als Reaktion darauf habe ich `chemgreek` am 13. März aktualisiert, um die neuen Befehle zu verwenden. Die Fahlermeldung bedeutet, dass Deine `chemgreek`-Version aktualler ist, als Deine `l3kernel`-Version. Ausweg: TeX-Distribution komplett aktualisieren.

**Comment by ryder1977** [comment]
Guten Morgen

mein MikTex ist aktuell, habe das gerade nochmal im Paketmanager 
überprüft. Gibt es so etwas wie einen Kompatibilitätsmodus in dem Paket?

Gruß

Am 03.04.2015 um 18:39 schrieb Clemens Niederberger:
>
> Hast Du etwa |chemgreek| aktualisiert, ohne die TeX-Distribution als 
> ganzes zu aktualisieren? |\str_upper_case:f| wurde am ersten März 2015 
> zu expl3 hinzugefügt und als Reaktion darauf habe ich |chemgreek| am 
> 13. März aktualisiert, um die neuen Befehle zu verwenden. Die 
> Fahlermeldung bedeutet, dass Deine |chemgreek|-Version aktualler ist, 
> als Deine |l3kernel|-Version. Ausweg: TeX-Distribution komplett 
> aktualisieren.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cgnieder/chemmacros/issues/3#issuecomment-89347286>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by cgnieder** [comment]
Das Minimalbeispiel

    \listfiles
    \documentclass{article}
    \usepackage{chemmacros}
    \begin{document}
   \end{document}

erzeugt (Stand 04. April 2015) folgende Liste imn der log-Datei:

     article.cls    2014/09/29 v1.4h Standard LaTeX document class
      size10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
    chemmacros.sty    2015/02/08 v4.7 loads of little helpers for chemists (CN)
       expl3.sty    2015/03/01 v5547 L3 programming layer (loader) 
    ...
    chemgreek.sty    2015/03/13 v0.5a interface for upright greek letters for use in chemistry (CN)

Wichtig hier die Version von `expl3` in Verbindung mit der Version von `chemgreek`!

**Comment by ryder1977** [comment]
Hat sich erledigt, danke.

Am 04.04.2015 um 17:18 schrieb Clemens Niederberger:
>
> Das Minimalbeispiel
>
> |\listfiles
> \documentclass{article}
> \usepackage{chemmacros}
> \begin{document}
> |
>
> \end{document}
>
> erzeugt (Stand 04. April 2015) folgende Liste imn der log-Datei:
>
> |  article.cls    2014/09/29 v1.4h Standard LaTeX document class
>    size10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
> chemmacros.sty    2015/02/08 v4.7 loads of little helpers for chemists (CN)
>     expl3.sty    2015/03/01 v5547 L3 programming layer (loader)
> ...
> chemgreek.sty    2015/03/13 v0.5a interface for upright greek letters for use in chemistry (CN)
> |
>
> Wichtig hier die Version von |expl3| in Verbindung mit der Version von 
> |chemgreek|!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cgnieder/chemmacros/issues/3#issuecomment-89594243>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com
