### ISSUE TITLE
\iupac in \title with achemso breaks with - being undefined

### ISSUE THREAD

**Issue by PhelypeOleinik** [cgnieder/chemmacros#30]
(from here: https://tex.stackexchange.com/q/518398/134574)

Due to a bad timing between `achemso` and `chemmacros`, the following
document errors:
```latex
\documentclass{achemso}
\usepackage{chemmacros}
\title{Study of \iupac{1,2-di|methyl|benzene}}
\begin{document}
\end{document}
```
because `achemso` appends `\maketitle` to `\document`, and only then
`chemmacros` (loads `etoolbox` and) officially starts the document. Then,
since the document is not tarted at the time `\maketitle` is used, the `-`
(and other symbols) are not defined when `\iupac` is used in the title, thus
they error.

It seems to me that it wouldn't harm to do
`\bool_set_true:N \l__chemmacros_in_document_bool` in the definition of
`\chemmacros_iupac:nn`, probably somewhere here:

https://github.com/cgnieder/chemmacros/blob/489695fbe9f752fa70984408b815856f0db8875c/chemmacros.module.nomenclature.code.tex#L713-L715

so that all definitions are there when needed. I don't think this would be
a problem since at this point typesetting is already allowed, and if `\iupac`
were to be used before that, then the `Missing \begin{document} error`
would kick in.

**Comment by cgnieder** [comment]
Thanks for this find!
