### ISSUE TITLE
Font issues with XeLaTeX and \p

### ISSUE THREAD

**Issue by jnnkB** [cgnieder/chemmacros#32]
Hi,

I'm trying to use your package with different fonts setup in XeLaTeX. Unfortunately I think it looks somewhat ugly when I use $\pH$ and similar commands. It doesn't seem to change to one font but rather use different ones.

# The code

```latex
%!TEX TS-program = xelatex

\documentclass{article}

% Load packages for fonts and unicode
\usepackage{fontspec,xltxtra,xunicode}

% Load math packages
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{unicode-math}

% Set language
\usepackage[ngerman]{babel}

\setmainfont{TeX Gyre Heros}
\setsansfont{TeX Gyre Heros}
\setmonofont{TeX Gyre Cursor}

% These commands doesn't seem to change anything related to the problem
\setmathfont{TeX Gyre Bonum}

\SetMathAlphabet\mathrm{normal}{TU}{TeX Gyre Bonum}{m}{n}
\SetMathAlphabet\mathbf{normal}{TU}{TeX Gyre Bonum}{bx}{n}
\SetMathAlphabet\mathit{normal}{TU}{TeX Gyre Bonum}{m}{it}

\usepackage{chemmacros}
\begin{document}


\(\pH\)

\(\pOH\)

\(\Ka\)

\(\Kb\)

\(\pKa\)

\(\pKb\)

\vspace{1em}

\pH

\pOH

\Ka

\Kb

\pKa

\pKb


\end{document}
```

# The result 

![test](https://user-images.githubusercontent.com/29376715/80983841-59d49d00-8e2d-11ea-8cf8-2a67ef483adf.png)

**Comment by cgnieder** [comment]
I get this warning from your MWE:

```
Package fontspec Warning: Font "TeXGyreBonum" does not contain requested
(fontspec)                Script "Math".
```

and a simple $K_s$ displays the same as `\Ka`.

This is not really a problem of `chemmacros` but a problem with your choice of fonts…

You can of course do

```latex
\chemsetup[acid-base]{
  eq-constant = \text{\textit{K}} ,
  K-acid = \text{s} ,
  K-base = \text{b}
}
```

which would use the text fonts for the constants but maybe you should rather search for a suiting math font instead that really works. [However, the only one available today seems to be Fira Math](https://tex.stackexchange.com/a/542133/5049).

```latex
\documentclass{article}
\usepackage{fontspec}

\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{unicode-math}

\usepackage[ngerman]{babel}

\setmainfont{TeX Gyre Heros}
\setsansfont{TeX Gyre Heros}
\setmonofont{TeX Gyre Cursor}
\setmathfont{Fira Math}[Scale=1.1]

\usepackage{chemmacros}

\begin{document}

\( K \) K

\bigskip

\(\pH \pOH \Ka \Kb \pKa \pKb\)

\bigskip

\pH \pOH \Ka \Kb \pKa \pKb

\end{document}
```

![image](https://user-images.githubusercontent.com/2248538/81047017-d9a84900-8eb9-11ea-8daf-6ddf0b3b48f4.png)


----

PS:
 - you don't need `xunicode`, see https://tex.stackexchange.com/a/78767/5049
 - `xltxtra` can cause problems, see https://tex.stackexchange.com/a/80028/5049

**Comment by jnnkB** [comment]
Hi,

Thanks a lot!

I loaded the wrong font in the previous code. I wanted to load the font 'TeX Gyre Bonum Math'. (see code below)

```latex
%!TEX TS-program = xelatex

\documentclass{article}

% Load packages for fonts
\usepackage{fontspec}

% Load math packages
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{unicode-math}

% Set language
\usepackage[ngerman]{babel}

\setmainfont{TeX Gyre Heros}
\setsansfont{TeX Gyre Heros}
\setmonofont{TeX Gyre Cursor}

\setmathfont{TeX Gyre Bonum Math}

\usepackage{chemmacros}
\begin{document}


\(\pH\)

\(\pOH\)

\(\Ka\)
$K_s$

\(\Kb\)

\(\pKa\)

\(\pKb\)

\vspace{1em}

\pH

\pOH

\Ka
$K_s$

\Kb

\pKa

\pKb


\end{document}
```

The output then shows the difference I meant. It partly uses the sans-serif font and partly the serif font. 

<img width="276" alt="image" src="https://user-images.githubusercontent.com/29376715/81048591-e7130280-8ebc-11ea-99dd-d907a420fed4.png">

And again thanks a lot for your notes and xunicode and xltxtra.

**Comment by cgnieder** [comment]
I am unsure what you actually want. “Somewhat ugly” is a quite subjective term. Your output looks like I expect it to look. 

Do you want everything to use the math fonts? The p? The H? The OH? The subscripts? Or only part of them?

**Comment by jnnkB** [comment]
I thought that everything should use math fonts. Can you explain why the p and s/b are not using math fonts.

**Comment by cgnieder** [comment]
Well, as is documented the subscripts *are* in math mode but use `\mathrm` (maybe you want to adapt the font setting for that, it seems to fall back to the roman text font). H and OH are typeset as atoms. How this is done is determined by how you have set the `formula` option. By default, this is determined by the `chemformula` package.

All this can be set through options. The only thing that cannot be changed right now (I'll add an option for future versions) is `p`. Although, it can, but with a hack:

```latex
\documentclass{article}
\usepackage{fontspec}

\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{unicode-math}

\usepackage[ngerman]{babel}

\setmainfont{TeX Gyre Heros}
\setsansfont{TeX Gyre Heros}
\setmonofont{TeX Gyre Cursor}
\setmathfont{TeX Gyre Bonum Math}

\usepackage{chemmacros}

\chemsetup{
  formula = chemformula ,
  acid-base/K-acid = s ,
  acid-base/K-base = b ,
  chemformula/font-spec = TeX Gyre Bonum Math
}

\ExplSyntaxOn
\cs_set:Npn \chemmacros_p_style:n #1 { \chemformula_chcpd:nn {} {#1} }
\ExplSyntaxOff

\begin{document}

\(\pH \pOH \Ka \Kb \pKa \pKb\)

\bigskip

\pH \pOH \Ka \Kb \pKa \pKb

\end{document}
```

**Comment by jnnkB** [comment]
Thanks a lot.
