### ISSUE TITLE
error while using siunts range-phrase command option

### ISSUE THREAD

**Issue by tsfg** [cgnieder/chemmacros#33]
As I described in  detail already at [stackexchange ](https://tex.stackexchange.com/questions/551039/unable-to-set-the-representation-option-of-the-to-range-phrase-while-using-s) (including a  workaround), using the range-phrase option of the \SIrange-command of siunitx within a chemical equation  (tested as top of an arrow) will cause errors.

used on MikTex
versions: 
chemmacros: 5.11
siunitx: 2.8b
chemformula: 4.15j

**Comment by cgnieder** [comment]
This is not a bug but an incorrect input as I've detailed in my answer to the linked question at tex.sx
