### ISSUE TITLE
iupac command and ligatures

### ISSUE THREAD

**Issue by tstone-1** [cgnieder/chemmacros#35]
As stated in the manual, `|` within `\iupac{}` commands will prevent the generation of ligatures and also insert some extra spacing. May I ask why this is the case, e.g. what the actual benefit is?

```
\documentclass{article}
\usepackage{chemmacros}

\begin{document}
\iupac{1,3|-Di|chlo|ro|f|fbenz|ene}

1,3-Dichloroffbenzene
\end{document}
```

will produce

![Screenshot 2020-07-12 18 49 25](https://user-images.githubusercontent.com/48162401/87252060-8da4f200-c470-11ea-944f-bb97d6154260.png)

While the manual also describes how the extra spacing could be adjusted/deactivated:

```
\chemsetup{
	nomenclature/break-space=0em,
	nomenclature/hyphen-pre-space=0em,
	nomenclature/hyphen-post-space=0em,
}
```

 I couldn't find an option to disable the prevention of ligatures. Is there a workaround?

BTW: There's a small typo in the manual of version 5.11; on page 14, it reads: 'The character = is printed ad \nonbreakinghyphen'

**Comment by cgnieder** [comment]
If you want to disable it you could either just leave the `|` away or define `\chemmacros_break_point:` to do nothing:

```latex
\cs_set:Npn \chemmacros_break_point: {}
```

**Comment by tstone-1** [comment]
```
\documentclass{article}
\usepackage{chemmacros}

\ExplSyntaxOn
\cs_set:Npn \chemmacros_break_point: {}
\ExplSyntaxOff

\begin{document}
\iupac{1,3|-Di|chlo|ro|f|fbenz|ene}



1,3-Dichloroffbenzene
\end{document}
```

gives

![Screenshot 2020-08-17 17 22 04](https://user-images.githubusercontent.com/48162401/90413048-3b2da580-e0ae-11ea-9dfc-cf7adb8cb9ee.png)

Thanks a lot for your advice. Actually, the border between IUPAC names and chemistry-related expressions became thin in some cases. Somehow, `\iupac{}` became one option to easily introduce breakpoints in some cases - at least for me.

**Comment by cgnieder** [comment]
IMHO when there is a break point there also should not be a ligature – a common problem in German:

```latex
\documentclass{article}
\usepackage[ngerman]{babel}

\begin{document}

Vorhofflattern (wrong) vs. \par
Vorhof"|flattern (right)

\end{document}
```

**Comment by tstone-1** [comment]
Very interesting, wasn't aware of this!
