### ISSUE TITLE
Extra dash appears sometimes in IUPAC names after \{element} macros.

### ISSUE THREAD

**Issue by myshevchuk** [cgnieder/chemmacros#39]
Hi!

In some edge cases an extra dash is inserted after `\{element}` macros:

``` tex
\documentclass{article}
\usepackage{chemmacros}

\begin{document}

Compounds with very long names such as in this example somecharsab
\iupac{\N-(\emph{tert}-nonsense)butverylongnametoglycosylamines} sometimes
produce an extra dash due to hyphenation.

\end{document}
```

<img width="1027" alt="Screenshot 2020-10-10 at 16 33 03" src="https://user-images.githubusercontent.com/24212814/95657722-46350d00-0b16-11eb-9d34-9259e52b2317.png">

Not in this case however:
``` tex
\documentclass{article}
\usepackage{chemmacros}

\begin{document}

Compounds with very long names such as in this example somecharsabc
\iupac{\N-(\emph{tert}-nonsense)butverylongnametoglycosylamines} sometimes
produce an extra dash due to hyphenation.

\end{document}
```

<img width="1014" alt="Screenshot 2020-10-10 at 16 36 18" src="https://user-images.githubusercontent.com/24212814/95657800-bcd20a80-0b16-11eb-9aa6-943eff407762.png">

Chemmacros v5.11 2020/03/07

`pdflatex -v` pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)

or

`lualatex -v` This is LuaHBTeX, Version 1.12.0 (TeX Live 2020)

**Comment by cgnieder** [comment]
This is because the opening parenthesis `(` adds a dash when a break happens directly before it. You can deactivate that behavior:

```latex
\documentclass{article}
\usepackage{chemmacros}
\RemoveChemIUPACShorthand(

\begin{document}

Compounds with very long names such as in this example somecharsab
\iupac{\N-(\emph{tert}-nonsense)butverylongnametoglycosylamines} sometimes
produce an extra dash due to hyphenation.

\end{document}

![image](https://user-images.githubusercontent.com/2248538/99908268-f5523000-2ce1-11eb-9291-43bc9583a813.png)

```

**Comment by myshevchuk** [comment]
Thank you very much for your help and the great packages!
