### ISSUE TITLE
Clash with beamerswitch

### ISSUE THREAD

**Issue by rafaelpap** [cgnieder/chemmacros#40]
The following example does not work 

```latex
\documentclass{beamerswitch}
\usepackage{upgreek}
\usepackage{chemmacros}
\usepackage[T1]{fontenc}      % european characters
\usepackage[utf8]{inputenc}

\begin{document}
\begin{frame}[shrink=15]%,plain]
\ch{Zn} and \ch{Cu\chemprime}
\end{frame}
\end{document}
```

just changing `beamerswitch` to `beamer` does work. 
The error message is

```latex
! Undefined control sequence.
<argument> ...formula_atom_format_tl Cu\chemprime 
                                                  \group_end: }
l.10 \end{frame}
```

I do not understand why `\chemprime` is not defined when using `beamerswitch`.
Thanks for the attention,
Rafael RP

**Comment by rafaelpap** [comment]
The author of beamerswitch offers the following explanation:

You will have seen from the manual that beamerswitch runs beamer with the ignorenonframetext option, and if you try your example with \documentclass[ignorenonframetext]{beamer}, you'll see that that is what causes the error.

Beamer goes to some trouble to make sure that the ignorenonframetext option injects the \mode* command late on in all the stuff that happens at \begin{document}, but it seems chemmacros manages to inject all its definitions even later, so they are ignored.

You have two relatively simple remedies. The easiest is to make chemmacros inject its stuff earlier than beamer:

\RequirePackage{chemmacros}
\documentclass{beamerswitch}
\usepackage{upgreek}
\usepackage[T1]{fontenc}
% etc.

The other is to undo the ignorenonframetext option, which requires a bit of knowledge of the internals, then apply the \mode command yourself:

\documentclass{beamerswitch}
\makeatletter\mode<presentation>{\beamer@ignorenonframefalse}\makeatother
\usepackage{upgreek}
% etc.
\begin{document}
\mode*
% etc.

**Comment by cgnieder** [comment]
Thanks for reporting and also for providing the explanation.

**Comment by cgnieder** [comment]
This might be solvable with a hook rule as declared by `\DeclareHookRule` but I have not been able to solve the problem with it. `chemmacros` simply does

```latex
\AddToHook{begindocument/end}{...}
```

Searching `beamer`'s code is a tiresome task…
