### ISSUE TITLE
\listofschemes not working in combination with the book class

### ISSUE THREAD

**Issue by Leandriis** [cgnieder/chemmacros#41]
While trying to answer this question [Create a simple “scheme” environment and a “List of Schemes”](https://tex.stackexchange.com/q/571810/134144), I stumbled upon `\listofschemes` resulting in a bunch of error messages when used in combination with the `book` class. The following MWE works perfectly fine with `article`, `report`, the KOMA-script classes (including `scrbook`)  and `memoir` but results in the error messages quoted below, when used with `book`. 

MWE:
```
\documentclass{book}

\usepackage{chemmacros}
\chemsetup{modules=scheme}

\begin{document}
\listofschemes
\end{document}
```

excerpt of the log file:

```
! Argument of \use:c has an extra }.
<inserted text> 
                \par 
l.7 \listofschemes
                  
I've run across a `}' that doesn't seem to match anything.
For example, `\def\a#1{...}' and `\a}' would produce
this error. If you simply proceed now, the `\par' that
I've just inserted will cause me to report a runaway
argument that might be the root of the problem. But if
your `}' was spurious, just type `2' and it will go away.

Runaway argument?
! Paragraph ended before \use:c was complete.
<to be read again> 
                   \par 
l.7 \listofschemes
                  
I suspect you've forgotten a `}', causing me to apply this
control sequence to too much text. How can we recover?
My plan is to forget the whole thing and hope for the best.
```

The above error messages were shown when compiling the MWE using an up to date MiKTeX (updated today).

**Comment by cgnieder** [comment]
Thanks! Fixed for the next update.
