### ISSUE TITLE
\theequation influences Reactions tag

### ISSUE THREAD

**Issue by el89barto** [cgnieder/chemmacros#50]
So for my thesis i changed the numbering of Equations to look like "Eq. 2.2-1" (Eq. chapter.section - 1).
I did this with the command `\renewcommand{\theequation}{Eq.\,\thesection-\arabic{equation}}`.
After changing this, I realized that my tags for reactions also have changed. 
Also I can't change the look of them with 
`\renewcommand{\thereaction}{R. \thesection-\arabic{reaction}}` which was able at the beginning of my writing.

Is there anything I'm missing?

**Comment by cgnieder** [comment]
Please provide a MWE. I cannot reproduce your issue.

```latex
\documentclass{article}
\usepackage{chemmacros}
\renewcommand{\theequation}{Eq.\,\thesection-\arabic{equation}}
\begin{document}

\begin{equation}
  1 + 3 = 4
\end{equation}

\begin{reaction}
  A + B -> C
\end{reaction}

\end{document}
```

gives

![grafik](https://user-images.githubusercontent.com/2248538/159728429-0734f466-7606-46de-9e67-3e3811e48ad8.png)

**Comment by el89barto** [comment]
```
\documentclass{thesisclass}

\usepackage{chemmacros} %Chemische formeln und Environments: https://ctan.org/pkg/chemmacros?lang=de
\chemsetup{modules=all, formula = mhchem, reactions/before-tag=R~,reactions/tag-open=(, reactions/tag-close=)}

\renewcommand{\thereaction}{R. \thesection-\arabic{reaction}}
\renewcommand{\theequation}{Gl.\,\thesection-\arabic{equation}}

\newcommand{\rxnref}[1]{Reaktion~\ref{#1}}
\newcommand{\eqxref}[1]{Gleichung~\ref{#1}}

\numberwithin{equation}{section} % This line resets equation numbering when starting a new section.
\numberwithin{reaction}{section}

\begin{document}
	
	\begin{equation}
		1+2 =3 \label{Eq-A}
	\end{equation}
	
	\theequation \\
	\eqxref{Eq-A}
	\begin{reaction}
		A + B -> C \label{R-A}
	\end{reaction}

	\thereaction \\
	\rxnref{R-A}
\end{document}
```
![grafik](https://user-images.githubusercontent.com/102238118/159731927-4a44cf64-8aea-47a3-a897-f22676bb5371.png)

[thesisclass..txt](https://github.com/cgnieder/chemmacros/files/8334170/thesisclass.txt)

**Comment by el89barto** [comment]
This is the template from my University together with the MWE, where the problem occurs.

**Comment by cgnieder** [comment]
I don't have your class so I can't test with it. Did you try _my_ example above?

In any case: your usage of `\chemsetup{modules=all}` suggest you are using an older version of `chemmacros`?

**Comment by el89barto** [comment]
I attached the class with the message above. As a txt File because .cls files were not alowed to upload. here is it again. I will try your suggestions
[thesisclass..txt](https://github.com/cgnieder/chemmacros/files/8334509/thesisclass.txt)
.

**Comment by cgnieder** [comment]
Thanks, I saw it later. Here is what I get (with an up to date TeX Live) from your code:

![grafik](https://user-images.githubusercontent.com/2248538/159742464-b3eaba33-4874-4129-a9ae-65f9ed5d4399.png)

If I move the `\renewcommand{\thereaction}...` assignments after the corresponding `\numberwithin` statements, I get:

![grafik](https://user-images.githubusercontent.com/2248538/159742813-8dd993f0-af8f-406d-b304-9c568b4024ea.png)

**Comment by el89barto** [comment]
Thank you very much. After reinstalling all updates in MikTex and some additional changes in my main preamble it works. Thank you! 👍
