### ISSUE TITLE
bug in new update to chemmacros

### ISSUE THREAD

**Issue by Leeser** [cgnieder/chemmacros#6]
Using one of the examples given in the manual, it no longer compiles, it was compiling up until yesterday. Is this possibly related to the [chemmacros error but output ok](http://tex.stackexchange.com/questions/266481/chemmacros-error-but-output-ok) I submitted on [tex.stackexchange.com](http://tex.stackexchange.com/questions/266481/chemmacros-error-but-output-ok)?

    \documentclass{article}
    \usepackage{chemmacros}
    \begin{document}
    \ch{
    \OX{a,Na} $\rightarrow$ \OX{b,Na}\pch\redox(a,b)[->,red]{ox}
    }
    \end{document}

I get the following errors: 

    ABD: EveryShipout initializing macros
    ./chemmacros2.tex:7: Undefined control sequence.
    <argument> \chemformula_font_inner: \OX 
                                            {a,Na}\c_math_toggle_token \rightarr...
    l.7 }
         
    ? 
    ./chemmacros2.tex:7: Undefined control sequence.
    <argument> ...\l__chemformula_math_space_skip \OX 
                                                      {b,Na}\pch \redox (a,b)[\c...
    l.7 }
         
    ? 
    ./chemmacros2.tex:7: Undefined control sequence.
    <recently read> \redox 
                           
    l.7 }
         
    ? 
    [1] (./chemmacros2.aux) )

**Comment by cgnieder** [comment]
add `\usechemodule{redox}` or `\usechemmocule{all}` to your preamble. There have been significant changes in v5.0, please have a look at the manual.

**Comment by cgnieder** [comment]
By the way: using `$\rightarrow$` and `\pch` inside of `\ch` doesn't make sense. The manual doesn't have this, either. It would be

```latex
\ch{\OX{a,Na} -> \OX{b,Na} {}+}
\redox(a,b){oxidation}
```
then.

**Comment by Leeser** [comment]
Hi,

I cut and pasted the example from the manual v5.0 2015/09/11 page 43. It is
also on page 42 3 times.

Anyhow, using \chemsetup{modules = all} has sorted the problem, thank you.
I will review the user manual for the newest version.

I use your packages extensively in my lectures and they are of enormous
use, so thank you for all your hard work, makes my LaTeXlife easier.

Leeser

**Comment by cgnieder** [comment]
I know the line is there but *not* within `\ch` :)

The new version also has
```latex
\usepackage[compatibility=4.7]{chemmacros}
```
in case you're in the middle of a project. This way you'd effectively use version 4.7 instead of 5.0.

**Comment by Leeser** [comment]
Ah, I see the error of my ways.

Re the compatibility=4.7, I will do that, refreshing versions of notes
going back a few years...

Must read manual!

Much appreciated..
