### ISSUE TITLE
Hapto and Dento should be superscripts

### ISSUE THREAD

**Issue by Canageek** [cgnieder/chemmacros#8]
`\bridge{1}`,` \dento{2}` and `\hapto{3}` all give subscripts, when `\dento{2}` and `\hapto{3}` should be superscripts. This can be seen in the current version of the manual or in the example below.

MWE showing the problem:
```
\documentclass{article}
\usepackage{chemmacros}
\begin{document}

\ch{\hapto{3}}
\ch{\dento{2}}
 
\end{document}
```

Output:
[chemmacrobugHaptoDento.pdf](https://github.com/cgnieder/chemformula/files/601154/chemmacrobugHaptoDento.pdf)

Source: 
[IUPAC Red Book 2005. IR-10.2.5.2 The eta (η) convention. (Page 216) and IR-9.2.4.2 The kappa convention (page 155-156 [see example bottom pg 156])](https://www.iupac.org/fileadmin/user_upload/databases/Red_Book_2005.pdf)

**Comment by cgnieder** [comment]
This will be corrected starting with version 5.8 (implemented in cset ab381b6a4f79f7435e32515f16a6c43a0fd0f430)
